CREATE EXTENSION pg_mustach;
SELECT 1, 'emptytag flag value', mustach_with_emptytag();
SELECT 2, 'equal flag value', mustach_with_equal();
SELECT 3, 'errorundefined flag value', mustach_with_errorundefined();
SELECT 4, 'escfirstcmp flag value', mustach_with_escfirstcmp();
SELECT 5, 'incpartial flag value', mustach_with_incpartial();
SELECT 6, 'jsonpointer flag value', mustach_with_jsonpointer();
SELECT 7, 'objectiter flag value', mustach_with_objectiter();
SELECT 8, 'partialdatafirst flag value', mustach_with_partialdatafirst();
SELECT 9, 'singledot flag value', mustach_with_singledot();
SELECT mustach_set_flags(mustach_with_noextensions());
SELECT 10, 'empty tag errors without EmptyTag extension', mustach('{}', '{{}}');
SELECT mustach_set_flags(mustach_with_allextensions());
SELECT 11, 'malformed delimiter directive', mustach('{}', '{{==}}');
SELECT 12, 'unescape tag missing closing brace', mustach('{}', '{{{name}}');
SELECT 13, 'unmatched closing tag', mustach('{}', '{{/x}}');
SELECT 14, 'mismatched closing tag name', mustach('{"a":{},"b":{}}', '{{#a}}{{/b}}');
SELECT mustach_set_flags(mustach_with_allextensions() | mustach_with_errorundefined());
SELECT 15, 'undefined tag errors with ErrorUndefined extension', mustach('{}', '{{missing}}');
SELECT mustach_set_flags(mustach_with_allextensions());
SELECT 16, 'excessive section nesting exceeds parser stack', mustach('{}', repeat('{{#s}}', 100));
SELECT 17, 'self-recursive partial exceeds nesting limit', mustach('{"loop": "{{>loop}}"}', '{{>loop}}');
SELECT 18, 'missing partial renders empty rather than erroring', mustach('{}', '{{>doesnotexist}}');
DROP EXTENSION pg_mustach;
