on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          client-payload: '{"repository": ${{ toJson(github.event.repository.name) }}}'
          event-type: latest
          repository: ${{ matrix.repo }}
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
    strategy:
      matrix:
        repo:
          - ${{ github.actor }}/postgres.docker
