name: Docker
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/github-repository-dispatch-action@v1
        with:
          client-payload: '{"repository": ${{ toJson(github.event.repository.name) }}}'
          event-type: latest
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
    strategy:
      matrix:
        repo:
          - postgres.docker
